### ISSUE TITLE
CastRemoteDisplay.CastRemoteDisplayApi.startRemoteDisplay not giving any result callback

### ISSUE THREAD

**Issue by NIkhilbadveli** [ankyl/castscreen#11]
`private void connectToRemoteDisplayApi() {
        PendingResult<CastRemoteDisplay.CastRemoteDisplaySessionResult> result = CastRemoteDisplay.CastRemoteDisplayApi.startRemoteDisplay(mApiClient, mAppId);

        result.setResultCallback(new ResultCallbacks<CastRemoteDisplay.CastRemoteDisplaySessionResult>() {
            @Override
            public void onSuccess(@NonNull CastRemoteDisplay.CastRemoteDisplaySessionResult castRemoteDisplaySessionResult) {
                Log.d(TAG, "Start remote display");
                Display remoteDisplay = castRemoteDisplaySessionResult.getPresentationDisplay();
                mPresentation = new PresentationService.CastScreenPresentation(mService, remoteDisplay, mProjectionManager);
                mPresentation.show();
                mPresentationShowing = true;

            }

            @Override
            public void onFailure(@NonNull Status status) {
                Log.d(TAG, "Stop Casting because startRemoteDisplay failed");
                deselectRoute();
            }
        });
    }`

I also checked if the mApiClient is null and it turned out to be a not null value. So, I don't understand why I'm not getting any result callback. Please help me. I really need to get this done fast.

Note: In the TV a blue cast icon is showing up in the middle. I don't know what this means.

**Comment by hard1k9850** [comment]
Hi @NIkhilbadveli 
Were you able to solve this issue?

**Comment by dhng22** [comment]
Is there any workaround for this issue?
