### ISSUE TITLE
Problems connecting with Bravia 4k 2015

### ISSUE THREAD

**Issue by CarLoOSX** [ankyl/castscreen#3]
I`ve tried in chromecast one and two myself succesfully but I've been reported that some people are unable to connect with Sony Bravia's Tv.

I've searching for this problem in google forums and I've seen lot of people who are experiencing problems.

Do you know what could be the issue? 

Sorry, I don't have any log or stacktrace. Seems to be connecting without poroblems but it doesn't.

Google Cast version: 1.19.63098.
Android Tv version: 5.1.1.
Build: SVP4KDTV15_EU-user 5.1.1 LMY48E.S265 3.533 release-keys.

Thank you so much.

**Comment by ankyl** [comment]
When does connection fail? Does the Cast icon show up? Can they reach the device selection prompt?

**Comment by CarLoOSX** [comment]
Hi!!
The connection doesn´t fail. They are able to select their Android Tv by clicking the icon but it seems to be allways connecting, the icon never stops the animation.

**Comment by ankyl** [comment]
Okay, I'm not sure what the problem is. Do you know if this can be reproduced with the [Cast Remote Display API sample](https://github.com/googlecast/CastRemoteDisplay-android)?

**Comment by CarLoOSX** [comment]
Completely working with the last bravia update.

I'm going to close the issue.
